Algoritmo "teste_enquanto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2022
Var
   x, soma: inteiro

Inicio
      escreva("Digite um número: ")
      leia(x)

      soma <- 15
      enquanto x <> 15 faca
         soma <- soma + x
         escreva("Digite outro número: ")
         leia(x)
      fimenquanto

      escreva("SOMA: ", soma)

Fimalgoritmo